### ISSUE TITLE
could not generate interface stub

### ISSUE THREAD

**Issue by BestNathan** [tooltitude/support#14]
Tooltitude Version: v0.23.1

OS Version: 22.3.0 Darwin Kernel Version 22.3.0

VS Code Version:1.78.2

Go Version:1.20.3

Code Repository (if open source):

What did you try to do?

Is there anything interesting in the tooltitude output channel? (should be open if you are reporting error from within VS Code)

Steps to reproduce
- Step 1: click `implement` above my struct
- Step 2: choose the interface i defined
- Step 3: check log output

![image](https://github.com/tooltitude/support/assets/26139217/7db844b1-a852-4c75-91f5-d3c66e403cc5)

**Comment by BestNathan** [comment]
when I downgrade to 0.22.5 this problem solved

**Comment by tooltitude-support** [comment]
@BestNathan Hi! Thanks for reporting! I will take a look at ti!

**Comment by tooltitude-support** [comment]
@BestNathan Is it possible to share a bit of the structure of your file? On obvious examples, it doesn't reproduce unfortunately.

**Comment by tooltitude-support** [comment]
Ok. I reproduced it. Will fix soon. It's enough to implement Context on a simple struct type.

**Comment by BestNathan** [comment]
> @BestNathan Also which interface do you implement? How many methods does it have? Does it have embedded interfaces?

@tooltitude-support 
hi bro, I meet something like this.

<img width="393" alt="image" src="https://github.com/tooltitude/support/assets/26139217/b5e08c2d-415c-409a-80d7-17b72902bed2">

as above, I have A implemented slog.LogValuer and B embed A, and then when I want to make B implement slog.LogValuer it doesn't generate the stub, obviously it treat that is already implemented, but what if I really want B implement itself, is that an expected result?

**Comment by tooltitude-support** [comment]
@BestNathan Ok, got your problem. I think in this situation it's logical to include stub implementations so that the user could choose which ones to leave. If VS Code had an API for more complicated dialogs, then it would make sense to present a choice.

**Comment by tooltitude-support** [comment]
@BestNathan I created a separate issue for your problem.
