### ISSUE TITLE
Extract Interface not working as expected

### ISSUE THREAD

**Issue by brennanjl** [tooltitude/support#16]
Tooltitude Version: v0.24.6

OS Version: Ventura 13.4

VS Code Version: 1.79.2

Go Version: 1.19

Code Repository (if open source): nil

What did you try to do?:  When extracting an interface from a struct, it does not properly handle variadic parameters. This causes the struct to not actually be compatible with the interface.  This is shown in the image below, where `Call(ctx context.Context, vars ...string)` is extracted as `Call(ctx context.Context, vars []string) error`:

![Screenshot 2023-06-29 at 2 47 53 PM](https://github.com/tooltitude/support/assets/66885902/40f3805e-5d7e-4109-95c8-eaec14a82031)

Is there anything interesting in the tooltitude output channel? (should be open if you are reporting error from within VS Code): No

Steps to reproduce
- Have a struct with variadic parameters in a method.
-  Extract the interface.

**Comment by tooltitude-support** [comment]
Ok. Thanks. This one is pretty easy to fix. Just in time before releasing the thing tomorrow.

**Comment by tooltitude-support** [comment]
Ok. It's fixed now. Will be out tomorrow.

**Comment by tooltitude-support** [comment]
Closing, since 0.25.0 is out.
