### ISSUE TITLE
Did a debug flag get left on in the latest release?

### ISSUE THREAD

**Issue by bradym** [tooltitude/support#17]
Tooltitude Version: 0.29.3

OS Version: Ubuntu 22.04.3 LTS

VS Code Version:

Version: 1.81.0
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:36:11.334Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.2.6-76060206-generic

Go Version:  
```
$ go version
go version go1.20.2 linux/amd64
```

What did you try to do?

Triggering code completion by hitting `.` after typing a type triggers an info box saying `ful_lsp=False`

![peek-2023-08-07](https://github.com/tooltitude/support/assets/289182/56ce23f6-c1cc-4be0-9ae2-f0ca7fb775bd)

**Comment by tooltitude-support** [comment]
@bradym Yep, it was left on. This is already fixed. Please update to 0.29.3
