### ISSUE TITLE
go.sum keeps being refreshed by Tooltitude.

### ISSUE THREAD

**Issue by ggqshr** [tooltitude/support#21]
Tooltitude Version:

v0.33.1

OS Version: 
Ubuntu 18.04.6 LTS

VS Code Version:
Version: 1.81.1 (user setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z

Go Version:
go version go1.19.9 linux/amd64

Code Repository (if open source):
None

What did you try to do?
Use git pull to sync remote commit, but go.sum keeps being refreshed by Tooltitude.
Use `git restore` to discard go.sum change, immediately after the go.sum change is discarded, it is refreshed by Tooltitude.
After disable Tooltitude, this phenomenon will no longer occur. 

Is there anything interesting in the tooltitude output channel? (should be open if you are reporting error from within VS Code)

Steps to reproduce
- enable tooltitude 
- `git restore .` 
- `git status` will see the go.sum diff
- repeat `git restore .`
- `git status` will always see the go.sum diff

**Comment by tooltitude-support** [comment]
Thank you for your feedback. 

May I ask you to revert go.mod file, and run go work sync (if you have a workspace file) or go mod download if you have just one module without tooltitude running? If go.sum files change, then they are likely out of date with the go.mod files.

You could disable this behavior with tooltitude.downloadDeps and tooltitude.workspaceSyncForDownload options (see their description for details about what they do).

There was a case like this here: https://github.com/tooltitude/support/issues/18

**Comment by tooltitude-support** [comment]
Closing the issue since we have an option to disable the described behavior, and there're no replies from the original reporter.
