### ISSUE TITLE
cannot disable "Unhandled Error" for `fmt.Println` and similar functions

### ISSUE THREAD

**Issue by asphaltbuffet** [tooltitude/support#22]
OS Version: 

> Edition	Windows 10 Pro
> Version	22H2
> OS build	19045.3448

VS Code Version: 

> Version: 1.83.0 (user setup)
> Commit: e7e037083ff4455cf320e344325dacb480062c3c
> Date: 2023-10-03T16:12:16.321Z

Go Version: 

> 1.21.0

Code Repository (if open source):

> n/a

Feature request:
- What is the problem you want to solve?
    - ![image](https://github.com/tooltitude/support/assets/30903912/93c7d59b-e2a5-4f39-b277-ef58f67276c7)
    - `fmt.Println()` always shows that error is not being checked. This is ignored by default by most tools (ie, errcheck). There is no documentation about ways to disable this or customize the errors. As a result, valid errors are drowned out in the noise.
- What did you try to solve it?
    - Checked documentation and extension settings for a way to modify. There do not appear to be any
    - Considered modifying function to explicitly ignore issue, it is too ugly: `_, _ = fmt.Println()`
- What you propose us to change in the product?
    - Ideally, use the `.golangci-lint.yml` file if present. Otherwise, give settings options to configure checks at a more granular level.

**Comment by tooltitude-support** [comment]
Thank you for your feedback.

It's not an error it's an information message. It's shown in case the method or function call returns an error, and this error result isn't handled in any way.  We will add an option to disable it in the next version (this Friday, 0.38.0).

**Comment by tooltitude-support** [comment]
@asphaltbuffet We will also, ignore fmt.* in the future. It makes very little sense to check for such errors.

**Comment by tooltitude-support** [comment]
@asphaltbuffet There're plenty of methods which return really possible errors in fmt, so we shouldn't ignore everything, just what's relevant. Likely fmt.Println,Print and similars.

**Comment by tooltitude-support** [comment]
@asphaltbuffet Ok. so in 0.38.0 we will:
- have tooltitude.unhandledErrorsEnabled option (true by default)
- ignore fmt.Println and fmt.Print for the purposes of this inspection

**Comment by tooltitude-support** [comment]
Closing due to the fact that it's fixed and out since Thu.
