### ISSUE TITLE
can not remove tooltitude shortcuts

### ISSUE THREAD

**Issue by BestNathan** [tooltitude/support#23]
Tooltitude Version: none

OS Version: 

VS Code Version:

Go Version:

Code Repository (if open source):

What did you try to do?

Is there anything interesting in the tooltitude output channel? (should be open if you are reporting error from within VS Code)

Steps to reproduce
- none

<img width="1283" alt="image" src="https://github.com/tooltitude/support/assets/26139217/2564a7d3-046e-4001-a02a-8bb003d4d208">

i do not know how to remove these keybinding shortcuts, and i try to uninstall tooltitude but not work, i can not remove or reset these shortcuts on vscode keyboard shortcuts management page

please help me out with some advises for solving this problem cause these shortcuts conflict with some other shortcuts which i use most

thanks a lot

**Comment by tooltitude-support** [comment]
@BestNathan thank you for your feedback.

To remove shortcuts, please right click on the shortcut and choose remove the keybinding.

<img width="601" alt="Screenshot 2023-10-06 at 9 10 42 AM" src="https://github.com/tooltitude/support/assets/123904466/1566bfc0-b9d3-411e-884f-055a463ce266">

BTW, which shortcut does tooltitude conflict with? Which extension does provide it?

**Comment by BestNathan** [comment]
> @BestNathan thank you for your feedback.
> 
> To remove shortcuts, please right click on the shortcut and choose remove the keybinding.
> 
> <img alt="Screenshot 2023-10-06 at 9 10 42 AM" width="601" src="https://user-images.githubusercontent.com/123904466/273217982-1566bfc0-b9d3-411e-884f-055a463ce266.png">
> BTW, which shortcut does tooltitude conflict with? Which extension provides them?

i have tried but not work 

but i notice that the source of shortcuts i snapshot before is `user` but i still can not remove them

conflict with `terminal: clear` which is a system shortcuts, i always use this shortcut to clear terminal text, but recently i found that it will wait for me to press second key like 
<img width="404" alt="image" src="https://github.com/tooltitude/support/assets/26139217/7910ce6a-de0b-4278-9b9c-c7afc71af888">

i follow the way from internet to find out why this happend and found that maybe our extension has conflict shortcuts, but when i try to edit, it didn't work

**Comment by BestNathan** [comment]
@tooltitude-support i followed a way to remove shortcuts from json file, https://stackoverflow.com/questions/33791097/how-can-i-change-keyboard-shortcut-bindings-in-visual-studio-code , it worked, thks

**Comment by tooltitude-support** [comment]
@BestNathan Interestingly on my machine there's a shortcut Cmd+K Cmd+S to open shortcut settings. Does this shortcut not conflict with Cmd+K for clearing the terminal?

**Comment by tooltitude-support** [comment]
@BestNathan I changed the shortcut condition by adding !terminalFocus to them. After that there will be no need to remove shortcuts anymore. It will be available in the next release, likely on Thu or Fri of the next week (0.39.0).

**Comment by BestNathan** [comment]
> @BestNathan I changed the shortcut condition by adding !terminalFocus to them. After that there will be no need to remove shortcuts anymore. It will be available in the next release, likely on Thu or Fri of the next week (0.39.0).

that's great, cause i found it conflicts again like
<img width="1327" alt="image" src="https://github.com/tooltitude/support/assets/26139217/4db0ef39-1ec7-4759-879b-7799c0d93749">

i found there are many conditions on terminal clear shorcuts

maybe adding `!terminalFocus` condition will work, let's see further!

**Comment by BestNathan** [comment]
@tooltitude-support I wonder what these shortcuts work for? cause i bearly use these shortcuts, `F12` is really difficult for me to press on, lol. maybe when the `editorTextFocus` condition fits these shortcuts purpose? or there are some other vscode panels that need these shortcuts?

**Comment by BestNathan** [comment]
> @BestNathan We released 0.39.0, please try it and let me know whether your problem repeats

it works so far, if there is any problem I will let you know, thanks a lot!
