### ISSUE TITLE
Tooltitude generates invalid code when discarding an error

### ISSUE THREAD

**Issue by bmarinov** [tooltitude/support#28]
When tooltitude rewrites a line in order to ignore an unhandled error, this results in invalid code being generated. The blank identifier cannot be declared, and the short var declaration operator `:=` should not be used.

Tooltitude Version: v0.44.0

OS Version: MacOS 13.6.1

VS Code Version: v1.84.2

Go Version: 1.21.4

**What did you try to do?**
Quick Fix => Ignore unhandled error in a test.

**Is there anything interesting in the tooltitude output channel? (should be open if you are reporting error from within VS Code)**
None that I could find, only generic INFO messages.

**Steps to reproduce**
- Step 1: Call a function returning an error e.g. `os.Setenv()`
- Step 2: Show Code Actions on the affected line (CTRL / CMD + .) 
- Step 3: Select "Ignore unhandled error" under the Rewrite options

```go
// example code:
os.Setenv("FOO_BAR_ENV", "seven")

// applying the fix results in this invalid snippet:
_ := Setenv("FOO_BAR_ENV", "seven")
// ^ no new variables on left side of :=
```

**Expected:**
```go
_ = Setenv("FOO_BAR_ENV", "seven")
```

**Comment by tooltitude-support** [comment]
@bmarinov It's fixed now. Will keep this issue opened until 0.45.0 release is out.
