### ISSUE TITLE
`Unhandled error` message in switch

### ISSUE THREAD

**Issue by d-enk** [tooltitude/support#29]
```go
package main

func F() error {
	return nil
}

func main() {
	switch err := F(); err { // Unhandled error
	case nil:
	default:
		panic(err)
	}
}
```

**Comment by tooltitude-support** [comment]
@d-enk Thanks for the feedback. Will investigate this issue now

**Comment by tooltitude-support** [comment]
It's no fixed. Will be out in 0.45.0 today.

**Comment by tooltitude-support** [comment]
v0.45.0 is out. Closing this issue.

⭐ Your Opinion Matters to Us!  Leave us a review. ⭐
-⚡ Open this link: https://marketplace.visualstudio.com/items?itemName=tooltitudeteam.tooltitude&ssr=false#review-details
- Press write a review
- Login with github (or MS account if you have one)
- Choose the number of stars ⭐  (and optionally write a review, this part is optional despite the red message)
