### ISSUE TITLE
[Feature] Display the struct type inheritance on type hover

### ISSUE THREAD

**Issue by D1360-64RC14** [tooltitude/support#30]
- OS Version: Ubuntu 22.04
- VS Code Version: 1.85.1
- Go Version: 1.21.5

### Feature request
- What is the problem you want to solve?

    When hovering a struct type, VSCode displays the struct content (fields and types), but if there's some struct inheritance the editor doesn't expand it, needing to manually inspect the sources to view the resulting struct.

- What you propose us to change in the product?

    While hovering some struct type with inheritance, display an option to show the complete struct result, with the fields from the inherited structs (also, showing from which struct they are inherited).

### Examples

> Original visualization
> ![image](https://github.com/tooltitude/support/assets/33406930/282a38c2-fa58-4882-b52a-4e97e83a2ac8)

> Example made up in GIMP
> ![image](https://github.com/tooltitude/support/assets/33406930/9e6d6e4e-2c55-49c3-a2e3-bcfa2afa2e3f)

**Comment by tooltitude-support** [comment]
@D1360-64RC14 Thank you for your feedback!

**Comment by D1360-64RC14** [comment]
Seems like it was implemented. Maybe should the @tooltitude-support close this issue, or the current implementation is unfinished?
![image](https://github.com/user-attachments/assets/53d07df8-86ff-457d-bd3d-5e12617d6215)

**Comment by tooltitude-support** [comment]
@D1360-64RC14 It's not us, it's likely gopls. I will close it then.
