### ISSUE TITLE
Unable to count specific implementations of the Golang generic interface

### ISSUE THREAD

**Issue by benz9527** [tooltitude/support#35]
![image](https://github.com/tooltitude/support/assets/109717800/2d473e33-1bc9-4bd3-86e6-a6019db6b565)

![image](https://github.com/tooltitude/support/assets/109717800/f1bf5c29-49c5-4065-9ed1-896b4a96160a)

Tooltitude Version:
v0.66.3
OS Version: 
Win11

VS Code Version:
![image](https://github.com/tooltitude/support/assets/109717800/d4f547eb-de21-4ad8-a365-ac2a5faf642a)

Go Version:
Go1.22.0

Code Repository (if open source):
https://github.com/benz9527/xboot

What did you try to do?
Count the generic interface implementations correctly.

**Comment by tooltitude-support** [comment]
I implemented partial fix (ignoring type constraints). It will be available in the next 0.67.0 release likely this Fri. I will see what I could do with the constraints:

<img width="625" alt="Screenshot 2024-03-20 at 1 35 11 PM" src="https://github.com/tooltitude/support/assets/123904466/1c96d009-3598-4c14-b634-a322a125d141">

**Comment by tooltitude-support** [comment]
@benz9527 I have taken look, and type constraints are also implementable, and I see no big problems with them.

**Comment by tooltitude-support** [comment]
@benz9527 The only type of interface which we can't support are interfaces without methods, i.e. interface { ~int }

**Comment by tooltitude-support** [comment]
@benz9527 I have taken look, and type constraints are also seems to be implementable, and I see no big problems with them.  We won't implement impls for interfaces without methods though. We might need to traverse the whole project to find them, which isn't a good solution.

**Comment by tooltitude-support** [comment]
@benz9527 I have taken look, and type constraints seem to be implementable, and I see no big problems with them. We won't implement impls for interfaces without methods though. We might need to traverse the whole project to find them, which isn't a good solution.

**Comment by benz9527** [comment]
Traversing the whole project may waste too much time. Like the goland implementation, it always builds caches, which makes goland use too much CPU and the UI run sluggishly. So I turn to use the vscode.

**Comment by tooltitude-support** [comment]
@benz9527 BTW, may be you miss some other features? If you miss them, feel free to share them in a comment or a separate issue. We also have a Discord chat: https://discord.gg/f9MHBXsVwr where you could discuss your ideas and problems in a more free form way.

**Comment by tooltitude-support** [comment]
@benz9527 After some research, handling type variable constraints seems to be quite complicated:

See for example:

```
type I[T comparable] interface {
  a(t T);
}

type S[T Reader] struct { ... }

func (s *S[T]) a(t T) { ... }
```

In this case some Ts implement interface, and some don't. (currently these constraints are ignored). It could even get more complicated, if S is something like this:
```
type S[T Reader] struct {
   readers []T
}
```

**Comment by benz9527** [comment]
> @benz9527 After some research, handling type variable constraints seems to be quite complicated:
> 
> See for example:
> 
> ```
> type I[T comparable] interface {
>   a(t T);
> }
> 
> type S[T Reader] struct { ... }
> 
> func (s *S[T]) a(t T) { ... }
> ```
> 
> In this case some Ts implement interface, and some don't. (currently these constraints are ignored). It could even get more complicated, if S is something like this:
> 
> ```
> type S[T Reader] struct {
>    readers []T
> }
> ```

Agree

**Comment by tooltitude-support** [comment]
0.67.0 is out. Closing this issue. 

Please, check that your case works there.

**Comment by tooltitude-support** [comment]
And again, thanks a lot for reporting bugs. Don't hesitate to report bug and ask for features in the future! We are really eager to fix bugs and implement new features (where it's reasonable).

I see your project is quite a generic heavy. It's quite hard to find such a project (there're some though, for example https://github.com/emirpasic/gods). Feel free to report issues with generics or type constraints you have.

**Comment by benz9527** [comment]
![image](https://github.com/tooltitude/support/assets/109717800/0688aefe-a867-4b05-8376-e2f67d533271)
 It works!

**Comment by benz9527** [comment]
> And again, thanks a lot for reporting bugs. Don't hesitate to report bug and ask for features in the future! We are really eager to fix bugs and implement new features (where it's reasonable).
> 
> I see your project is quite a generic heavy. It's quite hard to find such a project (there're some though, for example https://github.com/emirpasic/gods). Feel free to report issues with generics or type constraints you have.

Yep, I am the Javaer to Gopher. So I kept the habit of coding with generics.
