### ISSUE TITLE
Misreported "Unresolved Reference" when using Type Alias

### ISSUE THREAD

**Issue by YQSYZE** [tooltitude/support#38]
Tooltitude Version: v0.69.0

OS Version: macOS 12.7.2

VS Code Version: 1.88.0

Go Version:1.21.6

Code Repository (if open source):

What did you try to do?
![image](https://github.com/tooltitude/support/assets/44891180/4831fae4-75f9-488d-ba05-4336d2bc0597)

Is there anything interesting in the tooltitude output channel? (should be open if you are reporting error from within VS Code)

Steps to reproduce
- Step 1: Define a type alias, and define a method on type alias
- Step 2: Call the method
- Step 3: It can be compiled, but it will misreported "Unresolved Reference".

**Comment by tooltitude-support** [comment]
@YQSYZE Thanks for your feedback! Will take a look at it today!

**Comment by tooltitude-support** [comment]
@YQSYZE 
0.70.0 is out now. The issue should be fixed now. Please, reopen this issue if the issue repeats.
