### ISSUE TITLE
Method Tips About the standard package

### ISSUE THREAD

**Issue by iscraft** [tooltitude/support#43]
I use fmt package and tooltitude   

![1](https://github.com/user-attachments/assets/f9a8f703-f41f-4a70-b3c0-265b60bb7f53)  

disable tooltitude  

![2](https://github.com/user-attachments/assets/27e1c2db-305a-4e0e-929c-83d2ba581cca)  

what is print(expr)(tt) and println(expr)(tt)  
print and println is not in the fmt standard package  
Print and Println are the correct ones  

Tooltitude Version:  
0.92.2  
OS Version:   
windows 10  
VS Code Version:  
1.87.2  
Go Version:  
go version go1.23.0 windows/amd64

**Comment by tooltitude-support** [comment]
@iscraft Thanks for the feedback.

It's a postfix completion. The completion item should convert fmt.pr -> print(fmt) We probably should disable this item for packages.

**Comment by tooltitude-support** [comment]
@iscraft Ok. Fixed it. It will be out in 0.93.0, likely this Fri.

**Comment by tooltitude-support** [comment]
0.93.0. The issue is fixed there. Please let me know if it still reproduces.
