### ISSUE TITLE
Allow enabling/disabling specific lens

### ISSUE THREAD

**Issue by MaximKukushkin** [tooltitude/support#5]
Feature request:
- What is the problem you want to solve?
I only need one code lens provided by the extension, not all of them

- What did you try to solve it?
Looking for any settings for the extension. Seems like there're none

- What you propose us to change in the product?
Expose configuration settings which would allow to enable/disable specific code lens provide by the extension. For example, I only need the "run/debug" lens for the "main" functions. I don't really need the number of refs/implementations for all the components and would like to disable it.
Currently it's all or nothing.

**Comment by tooltitude-support** [comment]
Hello Maxim! Thanks for your feedback!

There're settings to choose lenses. Here're their names:
- tooltitude.refCodeLensEnabled
- tooltitude.implCodeLensEnabled

Please, let me know if these lenses are enough for you, if they are not, we could add more lenses.

Also, why you don't want to have other lenses? Are they slow? Or are they just occupying the space?
