### ISSUE TITLE
Server failed to start for too many times

### ISSUE THREAD

**Issue by rusgai** [tooltitude/support#7]
OS Version: 

VS Code Version:

Go Version:

Code Repository (if open source):

What did you try to do?

Is there anything interesting in the tooltitude output channel? (should be open if you are reporting error from within VS Code)

Steps to reproduce
- Step 1
- Step 2 
- Step 3

**Comment by tooltitude-support** [comment]
Hello Ruslan! Thank you for your feedback!

It would be great if you could share the contents of the tooltitude output channel. Especially interesting are the exceptions and details of what's your project look like. (You could use https://gist.github.com/)

**Comment by tooltitude-support** [comment]
Another thing of concern is the tooltitude version which you use. We had a problem leading to the language server termination before tooltitude v0.12.5. Please, make sure that you are at least on this version before reporting.

**Comment by tooltitude-support** [comment]
@rusgai did you try a new version? do you still experience this?
